name: Upload to Private PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Extract Metadata
        id: extract_metadata
        run: |
          # Extract metadata from the built wheel
          WHEEL_PATH=$(ls dist/*.whl)
          PACKAGE_NAME=$(python -c "from wheel.wheelfile import WheelFile; print(WheelFile('$WHEEL_PATH').parsed_filename.group('name'))")
          VERSION=$(python -c "from wheel.wheelfile import WheelFile; print(WheelFile('$WHEEL_PATH').parsed_filename.group('ver'))")
          DESCRIPTION=$(python -c "import tomli; print(tomli.load(open('pyproject.toml', 'rb'))['project']['description'])")
          echo "package_name=$PACKAGE_NAME" >> $GITHUB_ENV
          echo "description=$DESCRIPTION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Upload to Private PyPI
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        run: |
          curl -X POST "https://{{ domain }}/upload/" \
          -H "Authorization: Bearer $AUTH_TOKEN" \
          -F "file=@dist/*" \
          -F "title=${{ env.package_name }}" \
          -F "description=${{ env.description }}" \
          -F "version=${{ env.version }}"